#!/bin/bash
# Files that refer to this file by ID. (Backlinks)

ZKPATH="${ZKPATH:-~/Dropbox/wiki/archive}"

if [ ! -d "$ZKPATH" ]; then
  echo "Zettelkasten path \"$ZKPATH\" does not exist."
  exit 1
fi

if [ -z "$1" ]; then
  echo "You have to provide a filename"
  exit 1
fi

search_pattern=$(grep -o '[0-9]\+' <<< "$1")
rg "$search_pattern" "$ZKPATH" --files-with-matches | grep -v "$1"
