#!/bin/bash

ZKPATH="${ZKPATH:-~/Dropbox/wiki/archive}"

if [ ! -d "$ZKPATH" ]; then
  echo "Zettelkasten path \"$ZKPATH\" does not exist."
  exit 1
fi

if [ -z "$1" ]; then
  echo 'You have to provide something to search for'
  exit 1
fi

fd "$1" "$ZKPATH"
