#!/bin/bash

ZKPATH="${ZKPATH:-~/Dropbox/wiki/archive}"

if [ ! -d "$ZKPATH" ]; then
  echo "Zettelkasten path \"$ZKPATH\" does not exist."
  exit 1
fi

if [ -z "$1" ]; then
  echo "You need a search term."
  exit 1
fi

cmd=$(command -v rg || command -v ag || command -v grep)
$cmd "$1" "$ZKPATH"
