#!/bin/bash

ZKPATH="${ZKPATH:-~/Dropbox/wiki/archive}"

if [ ! -d "$ZKPATH" ]; then
  echo "Zettelkasten path \"$ZKPATH\" does not exist."
  exit 1
fi

if [ -z "$1" ]; then
  echo "Enter a tag to search for."
  exit 1
fi

cmd=$(command -v rg || command -v ag || command -v grep)
$cmd "$(printf "^tags: .*#%s" "$1")" "$ZKPATH" --files-with-matches
